
import Description from "@/components/Description"
import Landing from "@/components/Landing"
import Menu from "@/components/Menu"
import Location from "@/components/Location"
import Head from "next/head"
import Navbar from "@/components/Navbar"
import { Parallax } from "react-scroll-parallax"
import { ParallaxProvider } from "react-scroll-parallax"
import ScrollToTop from "react-scroll-to-top";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="appContainer">
        <Navbar />
     <div className="content">
      <ParallaxProvider>
      <Landing />
      <Parallax speed={-10}>
      <Description />
      <Menu />
      </Parallax>
      <Location />
      <ScrollToTop smooth />
      </ParallaxProvider>
     </div>
      </div>
    </>
  )
}
